<?php

namespace App\Services;

class QueueAudioService
{
    /**
     * Build audio playlist based on queue number and loket.
     * Matches the file structure generated by GenerateQueueVoices command.
     */
    public function buildPlaylist(string $queueNumber, string $loket): array
    {
        $playlist = [
            $this->getAudioUrl('umum/perhatian.mp3'),
            $this->getAudioUrl('umum/nomor-antrian.mp3'),
        ];

        // Bersihkan spasi/strip, lalu pisahkan prefix huruf dan angka
        // Contoh: "A - 001" -> prefix: "A", number: "001"
        $cleanNumber = trim(str_replace([' ', '-', '_'], '', $queueNumber));
        preg_match('/^([a-zA-Z]*)(\d+)$/', $cleanNumber, $matches);

        if ($matches) {
            $prefix = $matches[1];       // e.g. "A"
            $numberRaw = $matches[2];       // e.g. "001" (pertahankan leading zero)

            // 1. Prefix huruf (A, B, dst.)
            foreach (str_split(strtolower($prefix)) as $char) {
                $playlist[] = $this->getAudioUrl("huruf/{$char}.mp3");
            }

            // 2. Angka digit per digit menggunakan file angka/0.mp3 - angka/9.mp3
            // Contoh: "001" -> angka/0.mp3, angka/0.mp3, angka/1.mp3
            foreach (str_split($numberRaw) as $digit) {
                $playlist[] = $this->getAudioUrl("angka/{$digit}.mp3");
            }
        } else {
            // Fallback: karakter per karakter
            foreach (str_split(strtoupper($cleanNumber)) as $char) {
                if (ctype_alpha($char)) {
                    $playlist[] = $this->getAudioUrl('huruf/'.strtolower($char).'.mp3');
                } elseif (ctype_digit($char)) {
                    $playlist[] = $this->getAudioUrl("angka/{$char}.mp3");
                }
            }
        }

        $playlist[] = $this->getAudioUrl('umum/silakan-menuju.mp3');

        // 3. Loket (gunakan file loket/loket-{n}.mp3 yang sudah natural)
        preg_match('/\d+/', $loket, $loketMatches);
        $loketNum = $loketMatches[0] ?? 1;
        $playlist[] = $this->getAudioUrl("loket/loket-{$loketNum}.mp3");

        return $playlist;
    }

    protected function getAudioUrl(string $path): string
    {
        return asset('storage/audio/'.$path);
    }
}
