<?php

namespace App\Services;

class QueueAudioService
{
    /**
     * Build audio playlist based on queue number and loket.
     * Matches the file structure generated by GenerateQueueVoices command.
     */
    public function buildPlaylist(string $queueNumber, string $loket): array
    {
        $playlist = [
            $this->getAudioUrl('umum/perhatian.mp3'),
            $this->getAudioUrl('umum/nomor-antrian.mp3'),
        ];

        // Clean and parse (e.g., "A - 001" -> prefix: "A", number: 1)
        $cleanNumber = trim(str_replace([' ', '-', '_'], '', $queueNumber));
        preg_match('/^([a-zA-Z]*)(\d+)$/', $cleanNumber, $matches);

        if ($matches) {
            $prefix = $matches[1];
            $number = (int) $matches[2];

            // 1. Prefix letters
            if ($prefix) {
                foreach (str_split(strtolower($prefix)) as $char) {
                    $playlist[] = $this->getAudioUrl("huruf/{$char}.mp3");
                }
            }

            // 2. The number (plays the combined audio file, e.g., 20.mp3 for "020")
            $playlist[] = $this->getAudioUrl("angka/{$number}.mp3");
        } else {
            // Fallback: character by character if regex fails
            foreach (str_split(strtoupper($cleanNumber)) as $char) {
                if (ctype_alpha($char)) {
                    $playlist[] = $this->getAudioUrl("huruf/" . strtolower($char) . ".mp3");
                } elseif (is_numeric($char)) {
                    $playlist[] = $this->getAudioUrl("angka/{$char}.mp3");
                }
            }
        }

        $playlist[] = $this->getAudioUrl('umum/silakan-menuju.mp3');

        // 3. Loket audio (e.g., loket-1.mp3)
        preg_match('/\d+/', $loket, $loketMatches);
        $loketNum = $loketMatches[0] ?? 1;
        $playlist[] = $this->getAudioUrl("loket/loket-{$loketNum}.mp3");

        return $playlist;
    }

    protected function getAudioUrl(string $path): string
    {
        // Use relative path to avoid APP_URL mismatch issues in local dev
        return asset('storage/audio/' . $path);
    }
}
